name: Build InjectARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. Repository'yi çek
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. JDK 11'i kur
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # 3. Gradle Wrapper'ı çalıştırarak bağımlılıkları yükle ve projeyi derle
      - name: Build with Gradle
        run: ./gradlew build

      # 4. Derleme çıktısını arşivle
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: inject-arm64-build
          path: build/libs/
