name: Build APK for InjectARM64

on:
  workflow_dispatch: # Manuel tetikleme
    inputs:
      build_type:
        description: 'Choose the build type'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. Reponun checkout'lanması
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 11 kurulumu
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # 3. Android SDK ve gerekli araçların kurulumu
      - name: Set up Android SDK
        uses: reactivecircus/android-sdk-setup-action@v2
        with:
          sdk-version: 'commandlinetools-linux-8512546_latest'
          ndk-version: '22.1.7171670'
          target-sdk: '30'
          build-tools-version: '30.0.3'

      # 4. Gradle bağımlılıklarını yükle
      - name: Build with Gradle
        run: ./gradlew clean build -PbuildType=${{ github.event.inputs.build_type }}

      # 5. APK dosyasını arşivle
      - name: Archive APK file
        uses: actions/upload-artifact@v3
        with:
          name: inject-arm64-apk
          path: app/build/outputs/apk/${{ github.event.inputs.build_type }}/app-${{ github.event.inputs.build_type }}.apk
