name: Build InjectARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Bu satırı ekleyin, manuel çalıştırmayı etkinleştirir

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: inject-arm64-build
          path: build/libs/
